changelog:
  categories:
    - title: 🔥🔥 Breaking Changes 🔥🔥
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Fixes 🐛
      labels:
        - bug
    - title: Maintenance 👨‍💻
      labels:
        - dependencies
        - dev-ex
        - refactoring
    - title: Other Changes
      labels:
        - "*"
