name: 'dependency-cruiser report'
description: 'visualize dependenices of changed files in each pull request.'
author: 'MH4GF<h.miyagi.cnw@gmail.com>'
inputs:
  github-token:
    required: true
    description: 'A github access token'
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - id: changed-files
      uses: tj-actions/changed-files@v20
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
