name: 'dependency-cruiser report'
description: 'visualize dependenices of changed files in each pull request.'
author: 'MH4GF<h.miyagi.cnw@gmail.com>'
inputs:
  github-token:
    required: true
    description: 'A github access token'
    default: ${{ github.token }}
  config-file:
    required: false
    description: 'read rules and options from file (e.g. .dependency-cruiser.js)'
  cruise-script:
    required: true
    description: 'specify depcruise script (e.g. yarn depcruise)'
    default: yarn run -s depcruise
  working-directory:
    required: false
    description: 'running actions in another directory'
    default: '.'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - id: changed-files
      uses: tj-actions/changed-files@v35.9.2
      with:
        path: ${{ inputs.working-directory }}
        diff_relative: true
    - run: $GITHUB_ACTION_PATH/run.sh
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_TARGET_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        INPUT_CONFIG_FILE: ${{ inputs.config-file }}
        INPUT_CRUISE_SCRIPT: ${{ inputs.cruise-script }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
