import { PullRequest, Repo } from '../../type'

import { uniqueTag } from './uniqueTag'

// TODO
// - upload image to github
// - show commit hash
export const reportBody = (repo: Repo, pr: PullRequest) => {
  return `${uniqueTag({ ...repo, number: pr.number })}
# dependency-cruiser report

![graph](https://user-images.githubusercontent.com/31152321/168465804-f13b8cec-c480-40c7-9a5e-5fe3e28cb818.svg)

<p align="right">Report generated by [dependency-cruiser report action](https://github.com/MH4GF/dependency-cruiser-report-action)</p>
`
}
