import { describe, it, expect } from 'vitest'

import { reportBody } from './reportBody'

describe('reportBody', () => {
  it('should return body comment', () => {
    const owner = 'octocat'
    const repo = 'hello-world'
    const issueNumber = 1
    const sha = '8ef39983ce21a9c80821addbeb63bfe4d4068f9a'
    const expected = `<!-- This comment was generated by dependency-cruiser-report-action. id: 019eaab63a305793e5d15ee2a075d87c502951f24b8c24299aec60798ec0b2a6 -->
# dependency-cruiser report

visualize dependenices of changed files.

![graph](https://user-images.githubusercontent.com/31152321/168465804-f13b8cec-c480-40c7-9a5e-5fe3e28cb818.svg)

<p align="right">Report generated by <a href="https://github.com/MH4GF/dependency-cruiser-report-action">dependency-cruiser report action</a> ${sha}</a></p>
`
    expect(reportBody({ owner, repo, issueNumber, sha })).toBe(expected)
  })
})
