import { uniqueTag } from './uniqueTag'

type Params = {
  owner: string
  repo: string
  issueNumber: number
  sha: string
}

// TODO
// - upload image to github
export const reportBody = (params: Params) => {
  const url = 'https://github.com/MH4GF/dependency-cruiser-report-action'

  return `${uniqueTag({ owner: params.owner, repo: params.repo, issueNumber: params.issueNumber })}
# dependency-cruiser report

visualize dependenices of changed files.

![graph](https://user-images.githubusercontent.com/31152321/168465804-f13b8cec-c480-40c7-9a5e-5fe3e28cb818.svg)

<p align="right">Report generated by <a href="${url}">dependency-cruiser report action</a> ${
    params.sha
  } </p>
`
}
