import { describe, expect, it } from 'vitest'

import { uniqueTag } from './uniqueTag'

describe('uniqueTag', () => {
  it('should return tag with hashed id describing the workflow generated', () => {
    const context = {
      owner: 'octocat',
      repo: 'hello-world',
      issueNumber: 1,
      workingDirectory: 'src',
      cmdText:
        'yarn -s depcruise --output-type mermaid --config .dependency-cruiser.js dist/index.js src/options.ts',
    }
    const hashedId = '89253d8db6194825539b58ee117b84c7aba10898f5da899c54c0db435941f5f4'
    const tag = `<!-- This comment was generated by dependency-cruiser-report-action. id: ${hashedId} -->`
    expect(uniqueTag(context)).toBe(tag)
  })

  it('should work with extra key/value of passed object', () => {
    const context = {
      owner: 'octocat',
      repo: 'hello-world',
      issueNumber: 1,
      workingDirectory: 'src',
      cmdText:
        'yarn -s depcruise --output-type mermaid --config .dependency-cruiser.js dist/index.js src/options.ts',
      extra: 'foo',
    }
    const hashedId = '89253d8db6194825539b58ee117b84c7aba10898f5da899c54c0db435941f5f4'
    const tag = `<!-- This comment was generated by dependency-cruiser-report-action. id: ${hashedId} -->`
    expect(uniqueTag(context)).toBe(tag)
  })
})
