name: bump version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'major | minor | patch | premajor | preminor | prepatch | prerelease'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  tagging:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v4.0.1
      - run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          npm version ${{ github.event.inputs.version }}
          git push origin main --tag
