name: bump version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'major | minor | patch | premajor | preminor | prepatch | prerelease'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  tagging:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          npm version ${{ github.event.inputs.version }}
          git push origin main --tag
