on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@5378bfce550384e1e9a83504ab2a71df28cc6920 # main
      - run: pnpm run all
