name: 'check forbidden'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: MH4GF/shared-config/.github/composite-actions/setup-pnpm@main
        with:
          node-version-file: .node-version
          pnpm-version: '8.6.5'
      - run: pnpm i
      - run: pnpm exec depcruise src --config --output-type markdown >> $GITHUB_STEP_SUMMARY
