name: branch

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  content: write

jobs:
  release:
    uses: r7kamura/workflows/.github/workflows/keep-main-version-branch.yml@main
