name: tagpr
on:
  push:
    branches: "main"
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: Songmu/tagpr@3dca11e7c0d68637ee212ddd35acc3d30a7403a4 # v1.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
