name: tagpr
on:
  push:
    branches: "main"
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - uses: Songmu/tagpr@7ebae2dcc300132baa7cc9dd108c8923b07fc366 # v1.20.3
      id: run-tagpr
      env:
        GITHUB_TOKEN: ${{ secrets.MH4GF_PAT }}
    outputs:
      tagpr-tag: ${{ steps.run-tagpr.outputs.tag }}

  bump_major_branch:
    if: needs.tagpr.outputs.tagpr-tag != ''
    needs: tagpr
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Get major version
        run: echo "MAJOR_VERSION=$(echo ${{ needs.tagpr.outputs.tagpr-tag }} | cut -d '.' -f 1)" >> "$GITHUB_ENV"
      - name: Update major branch
        run: git push --force origin "HEAD:refs/heads/${MAJOR_VERSION}"
